// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webcoffee.Data;

#nullable disable

namespace webcoffee.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("webcoffee.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cà Phê"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trà"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sinh Tố"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đồ Ăn Nhẹ"
                        });
                });

            modelBuilder.Entity("webcoffee.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("webcoffee.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("webcoffee.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Cà phê đậm đà nguyên chất",
                            ImageUrl = "https://placehold.co/400x300?text=Espresso",
                            Name = "Espresso",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Espresso kết hợp với bọt sữa mịn",
                            ImageUrl = "https://placehold.co/400x300?text=Cappuccino",
                            Name = "Cappuccino",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Cà phê sữa kiểu Ý dịu nhẹ",
                            ImageUrl = "https://placehold.co/400x300?text=Latte",
                            Name = "Latte",
                            Price = 47000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Cà phê ủ lạnh thanh mát",
                            ImageUrl = "https://placehold.co/400x300?text=Cold+Brew",
                            Name = "Cold Brew",
                            Price = 50000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Trà xanh Nhật Bản tươi mát",
                            ImageUrl = "https://placehold.co/400x300?text=Tra+Xanh",
                            Name = "Trà Xanh",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Trà sữa thơm ngon kiểu Thái",
                            ImageUrl = "https://placehold.co/400x300?text=Tra+Sua+Thai",
                            Name = "Trà Sữa Thái",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Dâu tây tươi kết hợp sữa chua",
                            ImageUrl = "https://placehold.co/400x300?text=Sinh+To+Dau",
                            Name = "Sinh Tố Dâu",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Xoài chín mọng và nước cốt dừa",
                            ImageUrl = "https://placehold.co/400x300?text=Sinh+To+Xoai",
                            Name = "Sinh Tố Xoài",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Bánh bơ thơm giòn tan",
                            ImageUrl = "https://placehold.co/400x300?text=Banh+Sung+Bo",
                            Name = "Bánh Sừng Bò",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Bánh muffin đậm vị socola",
                            ImageUrl = "https://placehold.co/400x300?text=Muffin+Socola",
                            Name = "Muffin Socola",
                            Price = 37000m
                        });
                });

            modelBuilder.Entity("webcoffee.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            Name = "Bàn 1"
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            Name = "Bàn 2"
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            Name = "Bàn 3"
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            Name = "Bàn 4"
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = false,
                            Name = "Bàn 5"
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            Name = "Bàn 6"
                        },
                        new
                        {
                            Id = 7,
                            IsOccupied = false,
                            Name = "Bàn 7"
                        },
                        new
                        {
                            Id = 8,
                            IsOccupied = false,
                            Name = "Bàn 8"
                        },
                        new
                        {
                            Id = 9,
                            IsOccupied = false,
                            Name = "VIP 1"
                        },
                        new
                        {
                            Id = 10,
                            IsOccupied = false,
                            Name = "VIP 2"
                        });
                });

            modelBuilder.Entity("webcoffee.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị viên",
                            PasswordHash = "$2a$11$0Bo3V0kQ6MGqZILWXKBSPuvaoDcqB4a1/dSidaPMVDf0IHkeQPG3i",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("webcoffee.Models.Order", b =>
                {
                    b.HasOne("webcoffee.Models.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("webcoffee.Models.OrderDetail", b =>
                {
                    b.HasOne("webcoffee.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webcoffee.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("webcoffee.Models.Product", b =>
                {
                    b.HasOne("webcoffee.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webcoffee.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("webcoffee.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("webcoffee.Models.Table", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
